### ISSUE TITLE
Uppdatering av Stockholms lägerbidragsmall

### ISSUE THREAD

**Issue by tobbee** [Scouterna/skojjt#102]
Nuvarande lägerbidragsansökansmall för Stockholm är för höstterminen 2019. Den behöver modifieras så att den automatiskt byter till rätt termin (eller uppdateras manuellt varje halvår).

**Comment by TobbeEdgeware** [comment]
Klart med PR #113.

**Comment by tobbee** [comment]
Fixed by PR #113.
