### ISSUE TITLE
Gör medlemsnumret synligt

### ISSUE THREAD

**Issue by tobbee** [Scouterna/skojjt#107]
Medlemsnumret är användbart för att kunna logga in på scoutnet om man har flera barn så att mail-adressen inte är unik. Vore därför bra om man kunde se den i den i personvyn för en medlem. Just nu verkar inte medlemsnumret lagras i databasen.

**Comment by puggan** [comment]
* Lägg till medlemsnummer i persondatan (inte bara som nyckel)
* Presentera medlemsnummret i person-vyn.

**Comment by puggan** [comment]
Implemented, screenshoot from live-server.
![Screenshot from 2019-11-30 22-27-30](https://user-images.githubusercontent.com/866668/69906234-b2a49300-13c0-11ea-94b1-25b3f54c17e1.png)
