### ISSUE TITLE
Skepparcertifikat och märkestagning

### ISSUE THREAD

**Issue by tobbee** [Scouterna/skojjt#124]
Jag tänkte se till att försöka implementera någonting i den här vägen:

Möjlighet att spara delar mot märkestagning/skepparcertifikat och liknande enligt:

1. Centrala mallar för märken med delmoment (och bilder) Varje del har en kort och en lång beskrivning
2. Varje kår kan välja vilka märken den vill spåra. Kan baseras på mallar (efter ev. modifikation) eller vara helt nya.
3. På avdelningsnivå kan man markera vilka delar som godkänts. De sparas då med datum.
4. När alla delar är valda kan märket/certifikatet delas ut. Detta kan också markeras i Skojjt.
5. Märket/certifikatet skall också in Scoutnet. När det finns ett API för att plocka ut denna information, skall även den visas i Skojjt.

En tjänst som visar något av detta finns på https://minamarken.mikaelsvensson.info/
Synpunkter mottages tacksamt.

**Comment by tobbee** [comment]
Har kommit rätt långt med detta nu, så om någon är intresserad kan jag ge en demonstration. Har implementerat mallar på kårnivå och sen kan man på avdelningsnivå välja vilka märken man vill ha med en viss termin. Progress lagras på scoutnivå så att det följer med när man byter avdelning.

**Comment by martin-green** [comment]
Ja jag vill gärna se. Ska vi ta ett möte via teams?

**Comment by TobbeEdgeware** [comment]
Jobbar vidare efter diskussion med Martin igår. Borde finnas en PR inom ett par veckor

**Comment by TobbeEdgeware** [comment]
@martin-green  Nu har jag uppdaterat och börjar känna mig ganska klar. Har gjort en PR. Ska vi ta ett snack igen?

**Comment by tobbee** [comment]
Klart för tillfället i en första version, PR  #136.
