### ISSUE TITLE
isBoardMember() anser att alla som har behörighet till kårwebben tillhör styrelsen

### ISSUE THREAD

**Issue by puggan** [Scouterna/skojjt#127]
https://github.com/Scouterna/skojjt/blob/f01f9399e8708e45ec282d6ea2aa8e37e9239766/data.py#L257-L258

Då det i group_roles finns icke-styrelse relaterade behörigheter, så som att få access till kårwebben,
så fick vi ovanligt många i Föreningsredovisningen för styrelsen.

**Comment by martin-green** [comment]
Vilka roller ska anses vara en styrelse roll? Här är listan:
`2:e vice kårordförande
Anställd scoutkåren
Ansvarig Familjescout
Arkivansvarig
Arrangemangsansvarig
Av DS utsedd förvaltare
Besiktningsansvarig
Bidragsombud
Bokningsansvarig
Båtansvarig
Båtkommitté
Firmatecknare
Föräldraföreningens representant
Grenansvarig Bäverscout
Grenansvarig Spårarscout
Grenansvarig Upptäckarscout
Grenansvarig Utmanarscout
Grenansvarig Äventyrarscout
Grupp1
Grupp2
Grupp3
Grupp4
Grupp5
Hedersmedlem
Idrottsledare
Informatör
Intendent
Internationellt ombud
IT-ansvarig
JOTA/JOTI-ansvarig
Julmarknadskommitté
Kårkassör
Kårordförande
Kårpostmottagare
Kårsekreterare
Kårstyrelseledamot
Kårutbildare
Köansvarig
Ledare Övrig
Lokalansvarig
Lokalkommitté
Lägeransvarig
Lägerkommitté
Materielansvarig
Materielkommitté
Medlemsregistrerare
Nyanmälningar
Ombud funktionshinder
Planeringsansvarig
Redaktör
Rekryteringsansvarig
Revisor
Revisorssuppleant
Roverscout
Roverscoutledare
Scoutshopombud
Stugansvarig
Stugkommitté
Styrelsesuppleant
Säkerhetsansvarig
Tävlingsledare
Uppvaktningsansvarig
Uppvaktningskommitté
Utmanarscoutpostmottagare
Utmanarscoutrepresentant
Valberedning
Valborgskommitté
Webbansvarig
Vice kårkassör
Vice kårordförande
`

**Comment by kallemooo** [comment]
Olika kårer har olika definition på vilka roller styrelsemedlemmar har, och
det ändrar sig även med behoven i kåren.
En minimal definition kan vara Kårstyrelseledamot och Kårordförande Men med
stöd att lägga till och ta bort roller för kårerna själva.

För liknande funktion i Office365-Scoutnet-synk och Google-Scoutnet-synk så
används maillistfunktionen i scoutnet kunna styra vilka som ingår i gruppen.

**Comment by puggan** [comment]
I vår kår använder vi:
* Kårordförande
* Kårkassör
* Kårsekreterare
* Kårstyrelseledamot
* Styrelsesuppleant

Sen tycker jag att även dessa hör dit:
* Vice kårkassör
* Vice kårordförande

Men ser inga problem med att minimera det ner till:
* Kårordförande
* Kårstyrelseledamot
och kräva att om ni vill ha ut rätt värden i rapportern, så behöver ni sätta rollen "Kårstyrelseledamot" även på kassör mm.

**Comment by martin-green** [comment]
Styrelsemedlem är nu: Kårstyrelseledamot, Kårkassör, Kårordförande, Vice kårordförande, Kårsekreterare

**Comment by carlbjelksjo** [comment]
Inte så vanligt men en del kårer använder rollen 2:e vice kårordförande så den får gärna tas med också.
