### ISSUE TITLE
Skojjt fungerar konstigt, noterat från 2020-09-30

### ISSUE THREAD

**Issue by MagnusCalen** [Scouterna/skojjt#133]
Ber om hjälp att lösa problem/konstig funktionalitet. Det är inte bra för mig utan även för Jakob S som ha samma 'nya' symptom.

A) jag ser ej nytillagda användare i 'Kåraccess' och kan därför ej koppla dem till vår kår. 

B) jag ser bara två av kårens ca 300 medlemmar i personregistret. Dessa kan jag hantera i skojjt.

C) när jag tex går in i en avdelning och vill göra en person till ledare så blir resultatet efter markering 'gör till ledare' ett meddelande uppe i vänstra hörnet med texten "denied".

Eftersom detta verkar vara inte bara för mig som det strular så anar jag att det är något som bör åtgärdas centralt.

Jag är själv ej kodare/kunnig på området så ber om hjälp.

Jag är kåradmin för skojjt och har använt skojjt några år.

Tacksam för hjälp, återkoppling. Om ni önskar kontakta nås jag på 070-3125814 eller Magnus1@calen.nu.

**Comment by martin-green** [comment]
I personregistret så verkar alla personer utom 2 vara borttagna från scoutnet. Något konstigt måste ha hänt där. Hur ser det ut om du gör en ny import från scoutnet?

**Comment by MagnusCalen** [comment]
Hej Martin,

Tack har just kört ny inläsning, men felet/symptomen kvarstår.

 

Mvh

 

Magnus Calén 
Lerums Scoutkår, 070-3125814,  <mailto:magnus1@calen.nu> magnus1@calen.nu



http://www.lerumsscoutkar.se <http://www.lerumsscoutkar.se/> 

https://www.facebook.com/LerumsScoutkar/

 

 

 

 

Från: Martin Green <notifications@github.com> 
Skickat: den 19 oktober 2020 10:32
Till: Scouterna/skojjt <skojjt@noreply.github.com>
Kopia: MagnusCalen <magnus1@calen.nu>; Author <author@noreply.github.com>
Ämne: Re: [Scouterna/skojjt] Skojjt fungerar konstigt, noterat från 2020-09-30 (#133)

 

I personregistret så verkar alla personer utom 2 vara borttagna från scoutnet. Något konstigt måste ha hänt där. Hur ser det ut om du gör en ny import från scoutnet?

**Comment by martin-green** [comment]
Har kåren bytt namn i scoutnet?

**Comment by martin-green** [comment]
Är "Lerum KM scoutkår" samma sak som "Lerums scoutkår"?

**Comment by MagnusCalen** [comment]
Det vet jag eg inget om men tror ej det.
Hur kan jag kolla?

Med vänliga hälsningar
Magnus Calén, +46-70-3125814

19 okt. 2020 kl. 11:16 skrev Martin Green <notifications@github.com>:

﻿
Har kåren bytt namn i scoutnet?

**Comment by MagnusCalen** [comment]
Ja,
KM är gammalt och kommer från att vi tidigare var knutna till KFUK-KFUM.

Med vänliga hälsningar
Magnus Calén, +46-70-3125814

19 okt. 2020 kl. 12:23 skrev Martin Green <notifications@github.com>:

﻿
Är "Lerum KM scoutkår" samma sak som "Lerums scoutkår"?

**Comment by martin-green** [comment]
När ändrades det då?

Det finns ett 50-tal användare kopplade till Lerums KM. Jag kan ju börja 
med att flytta över dig.

Sen får vi fundera på varför det finns 2 scouter kvar i den gamla kåren...

/Martin

Den 2020-10-19 kl. 12:40, skrev MagnusCalen:

**Comment by MagnusCalen** [comment]
Hej Martin,

För mig känns inte ärendet avslutat.

Nu ser jag för visso flera personer i registret men all tidigare registrerad närvaro inkl denna termins närvaro är borta.

Jag ber dig ringa mig för att vi inte ska missförstå varandra.

Jag förstår ej vad du menar med nya respektive gamla kåren? Vi har bara en kår som är 75 år gammal.

Ja de verkar ha skett ett namnbyte i scoutnet. Men kårid och övrigt verkar vara det samma. Kan ändrat namn få dessa konsekvenser i skojjt?

Det är viktigt för mig att förstå vad som är orsaken till problemet så det inte händer igen.

Med vänliga hälsningar
Magnus Calén, +46-70-3125814

19 okt. 2020 kl. 22:33 skrev Martin Green <notifications@github.com>:

﻿
Closed #133.

**Comment by MagnusCalen** [comment]
Se svar nedan i kursiv text.

/MC

 

Från: Martin Green <notifications@github.com> 
Skickat: den 19 oktober 2020 13:02
Till: Scouterna/skojjt <skojjt@noreply.github.com>
Kopia: MagnusCalen <magnus1@calen.nu>; Author <author@noreply.github.com>
Ämne: Re: [Scouterna/skojjt] Skojjt fungerar konstigt, noterat från 2020-09-30 (#133)

 

När ändrades det då?

 

Är det när namnet ändrades i scoutnet som du menar med denna fråga? (Jag förstår inte riktigt vad du menar)


Det finns ett 50-tal användare kopplade till Lerums KM. Jag kan ju börja med att flytta över dig.

 

Till ’vilken kår’ flyttade du mig nu?

Effekten blev att jag nu ser fler medlemmar (troligen alla) men all registrerad närvaro är borta, denna termin liksom tidigare terminer.



Sen får vi fundera på varför det finns 2 scouter kvar i den gamla kåren...

/Martin

Den 2020-10-19 kl. 12:40, skrev MagnusCalen:
