### ISSUE TITLE
Startar fortfarande på gammal kår efter migrering till nytt namn

### ISSUE THREAD

**Issue by TobbeEdgeware** [Scouterna/skojjt#139]
Jag har flyttat vår kår från "S:t Göran, Sjöscoutkåren" till "Sjöscoutkåren S:t Göran" termin för termin genom att använda admin/merge_sg. Alla användar-data i UserPref är nu också på den "nya" kåren. Det enda som inte följde med vara lite data om kåren, som jag fick fylla i på nytt. 

Men, när man loggar in hamnar man fortfarande på den gamla kåren, och om jag tar bort gamla kåren i databasen går det inte ens att logga inutan då kraschar sidan och säger:

...
  File "/base/data/home/apps/e~stg-skojjt/20210206t214537.432890930104835102/start.py", line 62, in show
    breadcrumbs.append({'link':baselink, 'text':scoutgroup.getname()})
AttributeError: 'NoneType' object has no attribute 'getname'

Jag kan inte se i koden hur man kan hamna på den gamla kåren, det verkar inte hjälpa att ta bort login-cookien. När jag tittar på lista över kårer finns också bara den nya med. 

Vore tacksam för tips eller idéer om hur detta sista spår av det gamla kårnamnet kan tas bort.

**Comment by tobbee** [comment]
Nu, ett dygn senare, kommer jag inte till den gamla kåren trots att jag inte gjort någon ändring, så det verkar ha varit något som var cachat någonstans trots allt.

Stänger därför denna issue.
