### ISSUE TITLE
Epostadresser för föräldrar uppdateras inte pga ändringar i scoutnets api

### ISSUE THREAD

**Issue by hakankvist** [Scouterna/skojjt#150]
Hej!

Det verkar som om scounet ändrat nycklarna i apit för föräldrars e-postadresser.

Se förändring i scoutnet-google sync-skripten från Emil Öhman:
https://github.com/Scouterna/Google-Scoutnet-synk/pull/45/files

Troligtvis måste en liknande förändring göras i skojjt om jag skummar koden rätt.

**Comment by martin-green** [comment]
Jag har testat och det verkar funka som det ska.
Skojjt använder redan de fälten, se:
https://github.com/Scouterna/skojjt/blob/7080e8511f606c77ffad9ecaa65903f91ab52b2b/scoutnet.py#L64

**Comment by hakankvist** [comment]
Ok, då har jag gjort någonting fel.

Vi kör en gammal instans av skojjt men jag försökte söka igenom en nyclonad
git efter nyckeln innan jag la en felrapport.

Jag måste ha gjort fel någonstans.

Ursäkta för felaktig issue.

Den fre 17 sep. 2021 09:40Martin Green ***@***.***> skrev:
