### ISSUE TITLE
Säkerhetshål - man kan komma åt andra kårer genom att ha en scout som tillhört annan kår

### ISSUE THREAD

**Issue by vattlescout** [Scouterna/skojjt#165]
Upptäckte just att det går att komma åt en annan kårs inställningar och scouter om det är så att man har en scout som har tillhört en annan kår (som har skojjt kopplat till sig).
Jag upptäckte detta då jag av misstag råkade klicka in på en scout och fick då se en avdelning som jag visste att vi inte har hos oss - så klickade på den och vips så var jag inne på en annan kår och kan se alla deras scouter (inkl kontaktuppgifter) samt kan editera deras märken, möten och till och med editera deras importfiler. Vill förtydliga att jag inte har ändrat något eller laddat hem något medvetet.

Taggar admins här för att få säkerhetshålet tilltäppt:
@martin-green @tobbee @puggan @kesse @stefer @mrManner @kallemooo @benganellison @stalar @hakankvist

**Comment by mrManner** [comment]
@vattlescout Tack för rapporten, vi tittar på det direkt!

**Comment by mrManner** [comment]
@vattlescout skulle du kunna skicka medlemsnummer på din scout som bytt kår till `johan.manner@scouterna.se`?
