### ISSUE TITLE
Vem/vilka är administratörer för en kår?

### ISSUE THREAD

**Issue by stalar** [Scouterna/skojjt#169]
Jag är administratör för min kår, men kan jag se eller ändra vilka andra som är det?

(Finns det nåt bättre ställe än "Issues" att ställa frågor i?)

**Comment by Bulbakrut** [comment]
Finns det svar på detta?

**Comment by stalar** [comment]
Svaret jag fick när jag mailade Martin Green var att detta inte går att se eller ändra idag. Man kan ha flera administratörer, men Martin måste manuellt ändra vilka dessa är.

**Comment by Bulbakrut** [comment]
Ok. Har skickat epost får vi se om det går att fixa. Tack för återkoppling.

--

Christian Krut

Support Specialist

Viconia IT AB/Datacenter Dalsland

Direct: +46 530 759 130
________________________________
