### ISSUE TITLE
Json export

### ISSUE THREAD

**Issue by jschlyter** [Scouterna/skojjt#73]
Finns det något sätt att exportera avdelningars närvaro för en termin (eller år) som CSV eller JSON? Vi behöver omarbeta data lite innan export till kommunen (Lerum) och det vore smidigt att få ut all information samtidigt.

cc @stefer

**Comment by martin-green** [comment]
Har du provat den nya excel exporten: "Excelrapport"?

Den 2019-01-30 kl. 20:35, skrev Jakob Schlyter:

**Comment by jschlyter** [comment]
Mycket bättre, men lite besvärligt att tolka. Får man önska sig excelrapporten som JSON som alternativ? Skulle vara otroligt smidigt för oss som skall göra ytterligare analys.

**Comment by puggan** [comment]
Vad vill du ha ut ur json, som du inte får i csv exporten?

**Comment by jschlyter** [comment]
@puggan, Kön & personnummer

**Comment by puggan** [comment]
Ah, personnummer fanns tidigare, men då det försvann ur vyn med ärende 70, så kan javascriptet som genererar csv:n nå det.
https://github.com/martin-green/skojjt/issues/70

**Comment by martin-green** [comment]
Måste du ha personnummer?

**Comment by jschlyter** [comment]
@martin-green Personnumer behövs inte, men gärna medlemsnumret så vi kan korsreferera mot Scoutnet samt få en unik nyckel per person. Egentligen räcker medlemsnummer + vilka möten de varit med på - allt annat finns i Scoutnet.

**Comment by jschlyter** [comment]
@martin-green , har du någon uppdatering om detta? Excelrapporten med komplettering av personnummer och/eller kårid räcker, men väldigt gärna som JSON istället för Excel.

**Comment by martin-green** [comment]
Jag ska kolla på det i helgen. Jag gör en json export med samma data som excel.

**Comment by jschlyter** [comment]
Kan du få med ID-numret från scoutnet också så man kan korsreferera vore det toppen.

**Comment by jschlyter** [comment]
Fick du ihop något?

**Comment by martin-green** [comment]
Ja du kan prova nu.
