### ISSUE TITLE
Terminsprogram

### ISSUE THREAD

**Issue by puggan** [Scouterna/skojjt#98]
Definera en veckodag med tid, och skapa möten före hela terminen.

Närvarorapporteringen inte visar framtiden möten,
så att dagens möte hamnar först.

En vy som listar avdelningens alla möten, som kan vara publik, och användas som ett terminsprogram.

**Comment by vattlescout** [comment]
Jag tycker detta verkar vara en toppen idé - dock kan jag inget om detta och undrar därför hur det går med denna delen. Är det något som kommer komma eller är det bara kört?

**Comment by martin-green** [comment]
Du kan prova nu. Länken till terminsprogrammet finns på avdelningens sida.

**Comment by vattlescout** [comment]
> Du kan prova nu. Länken till terminsprogrammet finns på avdelningens sida. @vattlescout

Tack @martin-green. Har du en bra idé om hur man skriver det programmet (alltså formateringen)... :) Kanske framgår om jag kollar via datorn men på min Android så hittade jag inget vettigt när jag kollade på länken.

**Comment by martin-green** [comment]
Det är inte så mycket formatering, det är bara texten från mötesbeskrivningen formaterat med en enkel html sida. Vill du göra något mer avancerat finns det xml eller json.
Men man kan ju bygga ut det med markdown, men det får bli en annan task.
